# Generated by Django 4.1.3 on 2024-02-20 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.TextField()),
                ('goal_description', models.TextField()),
                ('task_description', models.TextField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.TextField(blank=True, null=True)),
                ('goal_created', models.DateTimeField(auto_now=True)),
                ('complete', models.BooleanField()),
                ('completed_on', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trioapi.category')),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_thoughts', models.TextField()),
                ('task_reflection', models.TextField()),
                ('learned', models.TextField()),
                ('do_differently', models.TextField()),
                ('take_away', models.TextField()),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trioapi.goal')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('difficulty', models.IntegerField()),
                ('repeat', models.BooleanField()),
                ('trio', models.BooleanField()),
                ('complete', models.BooleanField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trioapi.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trioapi.user')),
            ],
        ),
        migrations.CreateModel(
            name='JournalTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_tasks', to='trioapi.journal')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_journals', to='trioapi.task')),
            ],
        ),
        migrations.AddField(
            model_name='journal',
            name='hardest_tasks',
            field=models.ManyToManyField(through='trioapi.JournalTasks', to='trioapi.task'),
        ),
        migrations.AddField(
            model_name='journal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trioapi.user'),
        ),
        migrations.AddField(
            model_name='goal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trioapi.user'),
        ),
    ]
