# Generated by Django 4.1.3 on 2024-02-20 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trioapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
